game.AddParticles( "particles/deathbringer_fx.pcf" )
game.AddParticles( "particles/deathbringer_fx2.pcf" )

PrecacheParticleSystem("deathbringer_orb_core")
PrecacheParticleSystem("deathbringer_orb_core2")
PrecacheParticleSystem("deathbringer_orb_trail")
PrecacheParticleSystem("deathbringer_orb_fx")
PrecacheParticleSystem("deathbringer_orb_ring")
PrecacheParticleSystem("deathbringer_orb_sparks")
PrecacheParticleSystem("deathbringer_muzzle_main")
PrecacheParticleSystem("deathbringer_muzzle2")
PrecacheParticleSystem("deathbringer_muzzle3")
PrecacheParticleSystem("deathbringer_muzzle4")
PrecacheParticleSystem("deathbringer_muzzle5")
PrecacheParticleSystem("deathbringer_impact")
PrecacheParticleSystem("deathbringer_impact_glow")
PrecacheParticleSystem("deathbringer_impact_sparks")
