TFA.AddWeaponSound("TFA_MW2R_C4.Plant", {"weapons/tfa_mw2r/c4/wpn_h1_c4_bounce_01.wav", "weapons/tfa_mw2r/c4/wpn_h1_c4_bounce_02.wav"})
TFA.AddWeaponSound("TFA_MW2R_C4.Trigger", "weapons/tfa_mw2r/c4/wpn_h1_c4_trigger_plr.wav")
TFA.AddWeaponSound("TFA_MW2R_C4.Draw", "weapons/tfa_mw2r/c4/wpn_h1_c4_safetyoff_plr.wav")
TFA.AddWeaponSound("TFA_MW2R_C4.Holster", "weapons/tfa_mw2r/c4/wpn_h1_c4_safety_plr.wav")
TFA.AddWeaponSound("TFA_MW2R_C4.Toss", "weapons/tfa_mw2r/c4/toss.wav")