TFA.AddWeaponSound("TFA_MW2R_RIOT.Swing", {"weapons/tfa_mw2r/riotshield/riot_shield_melee_punch_03.wav", "weapons/tfa_mw2r/riotshield/riot_shield_melee_punch_04.wav"})
TFA.AddWeaponSound("TFA_MW2R_RIOT.Hit", {"weapons/tfa_mw2r/riotshield/riot_shield_impact01.wav", "weapons/tfa_mw2r/riotshield/riot_shield_impact02.wav"})
TFA.AddWeaponSound("TFA_MW2R_RIOT.Impact", {"weapons/tfa_mw2r/riotshield/h2_bulletimpact_riotshield_01.wav", "weapons/tfa_mw2r/riotshield/h2_bulletimpact_riotshield_02.wav", "weapons/tfa_mw2r/riotshield/h2_bulletimpact_riotshield_03.wav", "weapons/tfa_mw2r/riotshield/h2_bulletimpact_riotshield_04.wav"})
TFA.AddWeaponSound("TFA_MW2R_RIOT.Holster", "weapons/tfa_mw2r/riotshield/riot_shield_lower_weapon.wav")
TFA.AddWeaponSound("TFA_MW2R_RIOT.Lift", "weapons/tfa_mw2r/riotshield/riot_shield_raise_weapon.wav")
TFA.AddWeaponSound("TFA_MW2R_RIOT.Raise", "weapons/tfa_mw2r/riotshield/wpn_h2_riotshield_first_raise_01.wav")
TFA.AddWeaponSound("TFA_MW2R_RIOT.Look1", "weapons/tfa_mw2r/riotshield/wpn_h2_riotshield_inspect_look_1_01.wav")
TFA.AddWeaponSound("TFA_MW2R_RIOT.Look2", "weapons/tfa_mw2r/riotshield/wpn_h2_riotshield_inspect_look_2_01.wav")
TFA.AddWeaponSound("TFA_MW2R_RIOT.Rest", "weapons/tfa_mw2r/riotshield/wpn_h2_riotshield_inspect_look_rest_01.wav")
TFA.AddWeaponSound("TFA_MW2R_RIOT.Walk", {"weapons/tfa_mw2r/riotshield/riot_shield_plant_move_01.wav", "weapons/tfa_mw2r/riotshield/riot_shield_plant_move_02.wav", "weapons/tfa_mw2r/riotshield/riot_shield_plant_move_03.wav"})